name: hoge-fuga
on:
  push:
    branches:
      - master

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          git branch
          git log -3
          git status
          git pull
          git checkout "sandbox1"
          git log -3
          git status
          git merge origin/master --no-edit
          git push
          git status
      # - name: perform merge
