name: hoge-fuga
on:
  push:
    branches:
      - master

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: perform merge
        run: |
          # git config --global user.email "${GITHUB_ACTOR}"
          # git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          # git branch
          # git log -3
          # git status
          # git pull
          # git checkout "sandbox1"
          # git log -3
          # git status
          # git merge origin/master --no-edit
          # git push
          # git status
          for i in `seq 1 2`
          do
              BRANCH="sandbox${i}"
              git checkout $BRANCH
              git branch
              git pull
              git merge origin/master --no-edit && true
              if [ $? -eq 1 ]
              then
                  echo "conflict ${BRANCH}"
                  git status
                  git checkout --ours hoge.txt
                  git add hoge.txt
                  GIT_EDITOR=true git merge --continue
                  git push --set-upstream origin ${BRANCH}
              fi
              git push --set-upstream origin ${BRANCH}
              echo "merged to ${BRANCH}"
          done
